# Generated by Django 5.2.9 on 2025-12-14 20:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Institution",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("legal_name", models.CharField(max_length=255)),
                ("slug", models.SlugField(unique=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("PUBLIC", "Institution Publique"),
                            ("PRIVATE", "Institution Privée"),
                            ("INTERNATIONAL", "Organisation Internationale"),
                            ("UNIVERSITY", "Université"),
                            ("GOVERNMENT", "Gouvernement"),
                        ],
                        max_length=20,
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("website", models.URLField(blank=True)),
                ("address_line1", models.CharField(max_length=255)),
                ("address_line2", models.CharField(blank=True, max_length=255)),
                ("city", models.CharField(max_length=100)),
                ("postal_code", models.CharField(max_length=20)),
                ("country_code", models.CharField(max_length=2)),
                ("registration_number", models.CharField(blank=True, max_length=100)),
                ("tax_id", models.CharField(blank=True, max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "En attente de validation"),
                            ("ACTIVE", "Active"),
                            ("SUSPENDED", "Suspendue"),
                            ("REVOKED", "Révoquée"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("validated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="institutions/logos/"
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "validated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="validated_institutions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "institutions",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="InstitutionUser",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("ADMIN", "Administrateur"),
                            ("SIGNER", "Signataire"),
                            ("AUDITOR", "Auditeur"),
                            ("VIEWER", "Lecteur"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "institution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="institutions.institution",
                    ),
                ),
                (
                    "invited_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invited_users",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "institution_users",
            },
        ),
        migrations.AddIndex(
            model_name="institution",
            index=models.Index(
                fields=["status", "type"], name="institution_status_e64a4f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="institution",
            index=models.Index(
                fields=["country_code"], name="institution_country_1c7da4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="institution",
            index=models.Index(fields=["slug"], name="institution_slug_91ea43_idx"),
        ),
        migrations.AddIndex(
            model_name="institutionuser",
            index=models.Index(
                fields=["institution", "role"], name="institution_institu_874734_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="institutionuser",
            unique_together={("institution", "user")},
        ),
    ]
