# Generated by Django 5.2.9 on 2025-12-14 22:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("institutions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CryptographicKey",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("public_key", models.TextField()),
                ("fingerprint", models.CharField(max_length=128, unique=True)),
                (
                    "algorithm",
                    models.CharField(
                        choices=[
                            ("RSA_2048", "RSA 2048 bits"),
                            ("RSA_4096", "RSA 4096 bits (recommandé)"),
                            ("ECDSA_P256", "ECDSA P-256"),
                            ("ECDSA_P384", "ECDSA P-384 (recommandé)"),
                        ],
                        max_length=20,
                    ),
                ),
                ("key_size", models.IntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("EXPIRING_SOON", "Expire bientôt"),
                            ("EXPIRED", "Expirée"),
                            ("REVOKED", "Révoquée"),
                            ("ROTATED", "Remplacée par rotation"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("revocation_reason", models.TextField(blank=True)),
                ("validated_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "institution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="keys",
                        to="institutions.institution",
                    ),
                ),
                (
                    "parent_key",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rotated_keys",
                        to="cryptography.cryptographickey",
                    ),
                ),
                (
                    "validated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="validated_keys",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "cryptographic_keys",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="KeyRotation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "rotation_type",
                    models.CharField(
                        choices=[
                            ("SCHEDULED", "Rotation planifiée"),
                            ("MANUAL", "Rotation manuelle"),
                            ("SECURITY", "Rotation de sécurité"),
                            ("COMPROMISED", "Clé compromise"),
                        ],
                        max_length=20,
                    ),
                ),
                ("reason", models.TextField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "new_key",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rotations_to",
                        to="cryptography.cryptographickey",
                    ),
                ),
                (
                    "old_key",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rotations_from",
                        to="cryptography.cryptographickey",
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "key_rotations",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.AddIndex(
            model_name="cryptographickey",
            index=models.Index(
                fields=["institution", "status"], name="cryptograph_institu_55f24d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cryptographickey",
            index=models.Index(
                fields=["fingerprint"], name="cryptograph_fingerp_d5222a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cryptographickey",
            index=models.Index(
                fields=["expires_at"], name="cryptograph_expires_fd472c_idx"
            ),
        ),
    ]
