# Generated by Django 5.2.9 on 2025-12-14 19:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nom interne unique pour le template (ex: 'welcome_email_fr')",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "template_type",
                    models.CharField(
                        choices=[
                            ("WELCOME", "E-mail de bienvenue"),
                            ("PASSWORD_RESET", "Réinitialisation de mot de passe"),
                            ("EMAIL_VERIFICATION", "Vérification d'e-mail"),
                        ],
                        help_text="Type de template utilisé pour le déclenchement.",
                        max_length=50,
                    ),
                ),
                (
                    "subject",
                    models.CharField(help_text="Sujet de l'e-mail.", max_length=255),
                ),
                (
                    "body_text",
                    models.TextField(
                        blank=True, help_text="Corps de l'e-mail en format texte brut."
                    ),
                ),
                (
                    "body_html",
                    models.TextField(help_text="Corps de l'e-mail en format HTML."),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[("fr", "Français"), ("en", "English")],
                        default="fr",
                        max_length=5,
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        default=True,
                        help_text="Désactiver pour ne plus utiliser ce template.",
                    ),
                ),
            ],
            options={
                "db_table": "core_email_templates",
                "ordering": ["name"],
                "indexes": [
                    models.Index(
                        fields=["template_type", "language"],
                        name="core_email__templat_cab921_idx",
                    )
                ],
                "unique_together": {("template_type", "language")},
            },
        ),
    ]
