# Generated by Django 5.2.9 on 2025-12-14 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_emailtemplate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailtemplate",
            name="template_type",
            field=models.CharField(
                choices=[
                    ("WELCOME", "E-mail de bienvenue"),
                    ("PASSWORD_RESET", "Réinitialisation de mot de passe"),
                    ("EMAIL_VERIFICATION", "Vérification d'e-mail"),
                    ("DOCUMENT_REVOKED", "Document révoqué"),
                    ("KEY_EXPIRING", "Clé expirant bientôt"),
                ],
                help_text="Type de template utilisé pour le déclenchement.",
                max_length=50,
            ),
        ),
    ]
