# Generated by Django 5.2.9 on 2025-12-14 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_auditlog_action_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("LOGIN", "Connexion"),
                    ("LOGOUT", "Déconnexion"),
                    ("LOGIN_FAILED", "Échec connexion"),
                    ("SIGN", "Signature document"),
                    ("VERIFY", "Vérification document"),
                    ("REVOKE", "Révocation document"),
                    ("KEY_CREATED", "Création clé"),
                    ("KEY_ROTATED", "Rotation clé"),
                    ("KEY_REVOKED", "Révocation clé"),
                    ("INSTITUTION_VALIDATED", "Institution validée"),
                    ("INSTITUTION_SUSPENDED", "Institution suspendue"),
                    ("USER_UPD", "Utilisateur modifié"),
                ],
                max_length=50,
            ),
        ),
    ]
